server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info


spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:database/migration
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console